---
  - hosts: proxy
    become: true

    tasks:
      - name: Create wercker user
        user: name=wercker comment="Wercker" group=www-data

      - name: Add SSH key to wercker
        authorized_key: user=wercker key="{{ item }}"
        with_items:
          - "{{ lookup('file', './files/zen.pub') }}"
          - "{{ lookup('file', './files/paleo.pub') }}"

      - file: path=/var/www state=directory mode=0755

      - include: tasks/setup-nginx.yml
        vars:
          delete_default_vhost: true
          user: www-data
          worker_processes: "{{ ansible_processor_count }}"
          pid: /var/run/nginx.pid
          worker_connections: 768
      
      - include: tasks/setup-vhost-proxy.yml
        vars:
          name: "{{ item.name }}"
          service_ip: "{{ item.ip }}"
          service_port: 80
        with_items:
          - { name: 'ministerstwomilosci.pl', ip: 'ministerstwomilosci.pl.s3-website.eu-central-1.amazonaws.com' }
          - { name: 'pawelniewiadomski.com', ip: 'pawelniewiadomski.com.s3-website-us-west-2.amazonaws.com' }

      - include: tasks/setup-vhost-redirect.yml
        vars:
          name: pawelniewiadomski.pl
          redirect_url: http://pawelniewiadomski.com

      - include: tasks/setup-single-page-app.yml
        vars: 
          name: "{{ item }}"
        with_items:
          - usezen.it
          - czytojest.paleomenu.pl
          
    handlers:
      - include: handlers/handlers.yml

  - hosts: database
    become: true

    roles:
     - { role: gotansible.runit }

    tasks:
      - name: ensure apt cache is up to date
        apt: update_cache=yes
      - name: ensure packages are installed
        apt: name={{item}}
        with_items:
            - postgresql
            - postgresql-contrib
            - libpq-dev
            - python-psycopg2
            - xz-utils

  - hosts: database
    become: yes
    become_user: postgres
    gather_facts: no

    vars:
      dbname: "{{ db_name }}"
      dbuser: "{{ db_user }}"
      dbpassword: "{{ db_pass }}"

    tasks:
    - name: ensure database is created
      postgresql_db: name={{dbname}}

    - name: ensure user has access to database
      postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

    - name: ensure user does not have unnecessary privilege
      postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

    - name: add database extension
      postgresql_ext: name={{ item }} db={{ dbname }}
      with_items:
        - uuid-ossp

    - name: download postgrest
      become_user: root
      get_url: url=https://github.com/begriffs/postgrest/releases/download/v{{postgrest_version}}/postgrest-{{postgrest_version}}-ubuntu.tar.xz dest=/tmp mode=0400

    - name: extract postgrest
      become_user: root
      shell: cd /usr/local/bin && xzcat /tmp/postgrest-{{postgrest_version}}-ubuntu.tar.xz | tar -xf -
