---
  - hosts: proxy
    become: true

    tasks:
      - name: Create wercker user
        user: name=wercker comment="Wercker" group=www-data

      - name: Add SSH key to wercker
        authorized_key: user=wercker key="{{ item }}"
        with_items:
          - "{{ lookup('file', './files/zen.pub') }}"
          - "{{ lookup('file', './files/paleo.pub') }}"

      - file: path=/var/www state=directory mode=0755

      - include: tasks/setup-nginx.yml
        vars:
          delete_default_vhost: true
          user: www-data
          worker_processes: "{{ ansible_processor_count }}"
          pid: /var/run/nginx.pid
          worker_connections: 768
      
      - include: tasks/setup-vhost-proxy.yml
        vars:
          name: "{{ item.name }}"
          service_ip: "{{ item.ip }}"
          service_port: 80
        with_items:
          - { name: 'ministerstwomilosci.pl', ip: 'ministerstwomilosci.pl.s3-website.eu-central-1.amazonaws.com' }
          - { name: 'pawelniewiadomski.com', ip: 'ministerstwomilosci.pl.s3-website.eu-central-1.amazonaws.com' }

      - include: tasks/setup-vhost-redirect.yml
        vars:
          name: pawelniewiadomski.pl
          redirect_url: http://pawelniewiadomski.com

      - include: tasks/setup-single-page-app.yml
        vars: 
          name: "{{ item }}"
        with_items:
          - usezen.it
          - czytojest.paleomenu.pl
          
    handlers:
      - include: handlers/handlers.yml
