---
  - hosts: all

    tasks:
      - include: tasks/setup-nginx.yml
        become: true
        vars:
          delete_default_vhost: true
          user: www-data
          worker_processes: "{{ ansible_processor_count }}"
          pid: /var/run/nginx.pid
          worker_connections: 768
      
      - include: tasks/setup-vhost-proxy.yml
        become: true
        vars:
          name: ministerstwomilosci.pl
          service_ip: ministerstwomilosci.pl.s3-website.eu-central-1.amazonaws.com
          service_port: 80

      - include: tasks/setup-vhost-proxy.yml
        become: true
        vars:
          name: pawelniewiadomski.com
          service_ip: pawelniewiadomski.com.s3-website-us-west-2.amazonaws.com
          service_port: 80

      - include: tasks/setup-vhost-redirect.yml
        become: true
        vars:
          name: pawelniewiadomski.pl
          redirect_url: http://pawelniewiadomski.com

      - include: tasks/setup-single-page-app.yml
        become: true
        vars:
          name: usezen.it

    handlers:
      - include: handlers/handlers.yml
