---
  - name: "add nginx {{ name }} vhost"
    action: template src=templates/vhost-spa.j2 dest=/etc/nginx/sites-available/{{ name }}
    notify: restart nginx

  - name: "link nginx {{ name }} vhost in sites-enabled"
    action: file src=/etc/nginx/sites-available/{{ name }} dest=/etc/nginx/sites-enabled/{{ name }} state=link
    notify: restart nginx

  - file: path=/var/www/{{name}} state=directory mode=0775 owner=www-data group=www-data
